version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_DIALECT: sqlite
      DB_STORAGE: /app/database.sqlite
      LOGGING: info
    volumes:
      - ./backend:/app
      - db-data:/app/database.sqlite
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
